### PR TITLE
Tidy indentation

### PR DESCRIPTION
**Pull request by nick-jacobs**
Tidied up all the indentation to better clarify the structure of the html.

### CODE REVIEW

**Comment by surya-surendranath** [comment]
Hi nick,
Your indentation looks really good. just small changes to paragraphs, if you make <p> tags in separate line from line number (27-64), then it would be easy to identify the text area and will look more tidy.

**Comment by broc-harcourt** [comment]
Looks great, was interested to see the indentation of <p> tags below their corresponding <h1>, <h2>, etc tags. I hadn't seen this before. Seems to make sense in that content wise it defines the paragraphs that fall under a given header, but html tag wise the <p> tags don't nest with the <h> ones. So that was interesting to me.

**Comment by nick-jacobs** [comment]
That's true Broc, hadn't actually realised that they shouldn't be nested within header tags. I guessed I'd just assumed they were, as like you said, it kind of makes intuitive sense. But you're right, it doesn't need to be from an html perspective.

**Comment by broc-harcourt** [comment]
Looks great!

**Pull request merged**
